const PAPERS_CVD = [
  {
    color: '#7d2035',
    journal: "Alzheimer's & Dementia",
    jsub: "THE JOURNAL OF THE ALZHEIMER'S ASSOCIATION",
    doi: '10.1002/alz.71264',
    volume: "Alzheimers Dement. 2026;22(3):e71264",
    received: '6 October 2025', revised: '21 January 2026', accepted: '5 February 2026',
    title: 'Evolution of cortical cerebral microinfarcts on 3T MRI: risk factors and clinical relevance',
    authors: 'Jiannan Huang<sup>1</sup> &nbsp;|&nbsp; Christopher Chen<sup>2,3</sup> &nbsp;|&nbsp; Wei Ying Tan<sup>1</sup> &nbsp;|&nbsp; Jiangbo Cui<sup>2</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>2,3</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>4</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,2,3</sup>',
    affiliations: [
      'Saw Swee Hock School of Public Health, National University of Singapore and National University Health System, Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, National University of Singapore',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
    ],
    correspondence: 'Saima Hilal, Saw Swee Hock School of Public Health, NUS. Email: saimahilal@nus.edu.sg',
    abstract: [
      { h: 'INTRODUCTION', t: 'Cortical cerebral microinfarcts (CMIs) are associated with cognitive dysfunction and dementia, while their evolution on sequential MRI remains unclear.' },
      { h: 'METHODS', t: 'The study enrolled 490 patients (mean age 72.5 years) from a memory-clinic cohort with 5-year follow-up. Cortical CMIs were graded at baseline and year 2.' },
      { h: 'RESULTS', t: 'Forty-one (8.4%) patients showed incident cortical CMIs at year 2. Baseline cortical CMIs and large cortical infarcts showed the strongest association with incident CMIs.' },
      { h: 'DISCUSSION', t: 'Cortical CMI evolution may reflect dynamic changes in brain vascular pathology and represent a potential target for interventions aimed at preserving cognitive function.' },
    ],
    keywords: 'cerebral small vessel disease, cognitive dysfunction, dementia, epidemiology, neuroimaging',
  },
  {
    color: '#1a3a7a',
    journal: 'Hypertension Research',
    jsub: 'JAPANESE SOCIETY OF HYPERTENSION',
    doi: '10.1038/s41440-025-02435-1',
    volume: 'Hypertens Res. 2026;49(3):890-903',
    received: '22 July 2025', revised: '18 November 2025', accepted: '2 December 2025',
    title: 'Visit-to-visit blood pressure variability, brain MRI measures, and cognition in non-demented older adults',
    authors: 'Jiangbo Cui<sup>1,2</sup> &nbsp;|&nbsp; Caroline Robert<sup>1</sup> &nbsp;|&nbsp; An Qi Toh<sup>1</sup> &nbsp;|&nbsp; Eddie J Y Chong<sup>1,3</sup> &nbsp;|&nbsp; Joyce R Chong<sup>1</sup> &nbsp;|&nbsp; Yuan Cai<sup>1</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>4</sup> &nbsp;|&nbsp; Mitchell K P Lai<sup>1,3</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,3,5</sup> &nbsp;|&nbsp; Christopher Chen<sup>1,3</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Psychological Medicine, Yong Loo Lin School of Medicine, NUS',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
      'Saw Swee Hock School of Public Health, National University of Singapore',
    ],
    correspondence: 'Christopher Chen, Department of Pharmacology, NUS. Email: phccclh@nus.edu.sg',
    abstract: [
      { h: 'OBJECTIVE', t: 'Visit-to-visit blood pressure variability (BPV) has emerged as an independent risk factor for cardiovascular and cerebrovascular disease.' },
      { h: 'METHODS', t: 'Longitudinal data from 362 cognitively intact older adults were analysed with MRI markers of cerebrovascular disease and brain atrophy.' },
      { h: 'RESULTS', t: 'Higher systolic BPV was associated with worse cognitive outcomes. The relationship between SBPV and cognition was partially mediated by structural brain changes, with mediation proportions of 17–24% for cerebrovascular disease and 14–35% for brain atrophy.' },
      { h: 'CONCLUSIONS', t: 'BPV is a modifiable risk factor for cerebrovascular disease and cognitive decline, independent of mean blood pressure.' },
    ],
    keywords: 'blood pressure variability, brain atrophy, cerebrovascular disease, cognition',
  },
  {
    color: '#4a0e28',
    journal: 'Brain',
    jsub: 'OXFORD UNIVERSITY PRESS',
    doi: '10.1093/brain/awaf301',
    volume: 'Brain. 2025;148(11):3924-3934',
    received: '10 March 2025', revised: '5 June 2025', accepted: '20 June 2025',
    title: 'Synergistic effect between cortical cerebral microinfarcts and brain atrophy on cognitive decline',
    authors: 'Jiannan Huang<sup>1</sup> &nbsp;|&nbsp; Wei Ying Tan<sup>1</sup> &nbsp;|&nbsp; Jiangbo Cui<sup>2</sup> &nbsp;|&nbsp; Shin Hui On<sup>2</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>2,3</sup> &nbsp;|&nbsp; Christopher Chen<sup>2,3</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,2,3</sup>',
    affiliations: [
      'Saw Swee Hock School of Public Health, National University of Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
    ],
    correspondence: 'Saima Hilal, Saw Swee Hock School of Public Health, NUS. Email: saimahilal@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'Whether cortical cerebral microinfarcts (CMIs) and global brain atrophy interact synergistically in driving cognitive decline remains unknown.' },
      { h: 'METHODS', t: 'This longitudinal study examined 475 patients (mean age 72.7 years) from a memory clinic cohort over 5 years using 3-T MRI and neuropsychological assessments.' },
      { h: 'RESULTS', t: 'Cortical CMIs were associated with greater decrease over 2 years in total brain volume. Patients with high brain volume loss and cortical microinfarcts exhibited significantly lower cognitive scores in executive function, memory, language, and visuospatial function.' },
      { h: 'CONCLUSIONS', t: 'CMIs and neurodegeneration are mutually reinforcing pathological processes with implications for multi-target treatment strategies.' },
    ],
    keywords: 'brain volume, cerebral small vessel disease, cognitive dysfunction, dementia, neuroimaging',
  },
  {
    color: '#0d47a1',
    journal: 'Diabetes Care',
    jsub: 'AMERICAN DIABETES ASSOCIATION',
    doi: '10.2337/dc25-1162',
    volume: 'Diabetes Care. 2025',
    received: '1 June 2025', revised: '15 September 2025', accepted: '1 October 2025',
    title: 'White Matter Hyperintensities Moderate the Association Between Diabetes and Non-AD Brain Atrophy',
    authors: 'Jiangbo Cui<sup>1,2</sup> &nbsp;|&nbsp; Zhaojun Liu<sup>3</sup> &nbsp;|&nbsp; Wei Ying Tan<sup>4</sup> &nbsp;|&nbsp; Joyce R Chong<sup>1</sup> &nbsp;|&nbsp; Shin Hui On<sup>1</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>1,5</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>6</sup> &nbsp;|&nbsp; Mitchell K P Lai<sup>1,5</sup> &nbsp;|&nbsp; Christopher Chen<sup>1,5</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,4,5</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Psychological Medicine, Yong Loo Lin School of Medicine, NUS',
      'China-Japan Friendship Hospital, Beijing, China',
      'Saw Swee Hock School of Public Health, National University of Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
    ],
    correspondence: 'Saima Hilal, Saw Swee Hock School of Public Health, NUS. Email: saimahilal@nus.edu.sg',
    abstract: [
      { h: 'OBJECTIVE', t: 'This study examined how white matter hyperintensities (WMHs) moderate the relationship between diabetes and brain atrophy.' },
      { h: 'METHODS', t: 'Two cohorts without dementia were analyzed with MRI and cognitive assessments.' },
      { h: 'RESULTS', t: 'Diabetes and WMHs synergistically contribute to brain atrophy independent of Alzheimer disease pathology. The interaction was significant for hippocampal and total brain volumes.' },
      { h: 'CONCLUSIONS', t: 'Cerebrovascular disease rather than Alzheimer pathology drives cognitive decline in diabetic patients, highlighting the importance of vascular risk management.' },
    ],
    keywords: 'white matter hyperintensities, diabetes, brain atrophy, cerebrovascular disease, Alzheimer disease',
  },
  {
    color: '#8b4513',
    journal: 'Atherosclerosis',
    jsub: 'ELSEVIER',
    doi: '10.1016/j.atherosclerosis.2025.120472',
    volume: 'Atherosclerosis. 2025;409:120472',
    received: '15 January 2025', revised: '10 April 2025', accepted: '25 April 2025',
    title: 'Effect of metabolic syndrome severity on cerebral haemodynamics and cognition in community-based cohort',
    authors: 'Mervin Tee<sup>1</sup> &nbsp;|&nbsp; Mathijs B J Dijsselhof<sup>2</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>3,4</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>5</sup> &nbsp;|&nbsp; Christopher Chen<sup>3,4</sup> &nbsp;|&nbsp; Jan Petr<sup>2</sup> &nbsp;|&nbsp; Henk J M M Mutsaerts<sup>2</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,3,4</sup>',
    affiliations: [
      'Saw Swee Hock School of Public Health, National University of Singapore',
      'Department of Radiology and Nuclear Medicine, Amsterdam UMC, Netherlands',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
    ],
    correspondence: 'Saima Hilal, Saw Swee Hock School of Public Health, NUS. Email: saimahilal@nus.edu.sg',
    abstract: [
      { h: 'OBJECTIVE', t: 'This study examined how the severity of metabolic syndrome relates to cerebral haemodynamics and cognitive function using ASL-MRI in 602 older adults.' },
      { h: 'RESULTS', t: 'A paradoxical relationship was found where higher cerebral blood flow correlated with metabolic syndrome severity in lower-risk individuals, but lower flow in higher-risk individuals. Higher cMETS was associated with poorer global cognition.' },
      { h: 'CONCLUSIONS', t: 'Cerebral blood flow mediated approximately 43.5% of the metabolic syndrome–cognition relationship, highlighting haemodynamics as an intervention target.' },
    ],
    keywords: 'ageing, arterial spin labelling, cerebral blood flow, cognitive function, metabolic syndrome',
  },
  {
    color: '#555555',
    journal: 'Journal of the American Heart Association',
    jsub: 'AHA / ASA',
    doi: '10.1161/JAHA.124.035133',
    volume: 'J Am Heart Assoc. 2024;13(22):e035133',
    received: '10 March 2024', revised: '5 August 2024', accepted: '20 August 2024',
    title: 'Associations of Circulating Platelet Endothelial Cell Adhesion Molecule-1 Levels With Progression of Cerebral Small-Vessel Disease, Cognitive Decline, and Incident Dementia',
    authors: 'Ming Ann Sim<sup>1,2</sup> &nbsp;|&nbsp; Eugene S J Tan<sup>1,3</sup> &nbsp;|&nbsp; Siew Pang Chan<sup>4</sup> &nbsp;|&nbsp; Yuan Cai<sup>1</sup> &nbsp;|&nbsp; Yuek Ling Chai<sup>1</sup> &nbsp;|&nbsp; Joyce Ruifen Chong<sup>1</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>1,2</sup> &nbsp;|&nbsp; Caroline Robert<sup>1</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>5</sup> &nbsp;|&nbsp; Boon Yeow Tan<sup>6</sup> &nbsp;|&nbsp; Mitchell K P Lai<sup>1,2</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,2,7</sup> &nbsp;|&nbsp; Christopher L H Chen<sup>1,2</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'National University Heart Centre Singapore',
      'Department of Medicine, Yong Loo Lin School of Medicine, NUS',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
      "St. Luke's Hospital, Singapore",
      'Saw Swee Hock School of Public Health, National University of Singapore',
    ],
    correspondence: 'Christopher Chen, Department of Pharmacology, NUS. Email: phccclh@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'Circulating PECAM-1 reflects endothelial integrity and vascular inflammation, and may serve as a blood-based biomarker for cerebral small vessel disease.' },
      { h: 'METHODS', t: 'Plasma PECAM-1 levels and cerebral small-vessel disease progression were examined in dementia-free subjects followed over five years.' },
      { h: 'RESULTS', t: 'Lower PECAM-1 tertiles correlated with greater white matter hyperintensity volume and cerebral microbleeds. Those in lower PECAM-1 tertiles showed significantly higher incident dementia risk.' },
      { h: 'CONCLUSIONS', t: 'PECAM-1 is a clinically accessible blood-based biomarker for monitoring cSVD progression and cognitive decline.' },
    ],
    keywords: 'PECAM-1, CD31, cerebral small-vessel disease, cognition, dementia, endothelium',
  },
  {
    color: '#2e7d32',
    journal: "Alzheimer's Research & Therapy",
    jsub: 'BIOMED CENTRAL',
    doi: '10.1186/s13195-024-01577-7',
    volume: 'Alzheimers Res Ther. 2024;16(1):214',
    received: '14 March 2024', revised: '12 August 2024', accepted: '3 September 2024',
    title: 'Interactive effect of diabetes mellitus and subclinical MRI markers of cerebrovascular disease on cognitive decline and incident dementia: a memory-clinic study',
    authors: 'Jiangbo Cui<sup>1,2</sup> &nbsp;|&nbsp; Caroline Robert<sup>1</sup> &nbsp;|&nbsp; Chia May Teh<sup>1</sup> &nbsp;|&nbsp; Eddie Chong Jun Yi<sup>1,3</sup> &nbsp;|&nbsp; Joyce R Chong<sup>1</sup> &nbsp;|&nbsp; Boon Yeow Tan<sup>4</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>5</sup> &nbsp;|&nbsp; Mitchell K P Lai<sup>1,3</sup> &nbsp;|&nbsp; Christopher Chen<sup>1,3</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,3,6</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Psychological Medicine, Yong Loo Lin School of Medicine, NUS',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      "St. Luke's Hospital, Singapore",
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
      'Saw Swee Hock School of Public Health, National University of Singapore',
    ],
    correspondence: 'Saima Hilal, Saw Swee Hock School of Public Health, NUS. Email: saimahilal@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'The mechanisms underlying the association between diabetes and cognitive impairment remain poorly understood, particularly the role of cerebrovascular disease as an intermediary.' },
      { h: 'METHODS', t: '614 participants with baseline MRI and longitudinal cognitive testing over five years were examined for interactive effects of diabetes and white matter hyperintensities.' },
      { h: 'RESULTS', t: 'An interactive effect of diabetes and WMHs, rather than an independent effect, was found on cognitive decline. The association was stronger in participants with high white matter hyperintensity burden.' },
      { h: 'CONCLUSIONS', t: 'Diabetes effects on cognition depend on white matter hyperintensity presence and remain unchanged after adjusting for blood-based Alzheimer biomarkers.' },
    ],
    keywords: 'cerebrovascular disease, cognitive dysfunction, diabetes, magnetic resonance imaging',
  },
  {
    color: '#2a5f5f',
    journal: "Journal of Alzheimer's Disease",
    jsub: 'IOS PRESS',
    doi: '10.3233/JAD-220971',
    volume: 'J Alzheimers Dis. 2023;92(2):445-455',
    received: '5 September 2022', revised: '22 November 2022', accepted: '12 December 2022',
    title: 'Association of Interleukin-6 and Interleukin-8 with Cognitive Decline in an Asian Memory Clinic Population',
    authors: 'Nicole Shu Ning Teoh<sup>1</sup> &nbsp;|&nbsp; Bibek Gyanwali<sup>1</sup> &nbsp;|&nbsp; Mitchell K P Lai<sup>2,3</sup> &nbsp;|&nbsp; Yuek Ling Chai<sup>2</sup> &nbsp;|&nbsp; Joyce R Chong<sup>2</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>2,3</sup> &nbsp;|&nbsp; Christopher Chen<sup>2,3</sup> &nbsp;|&nbsp; Chuen Seng Tan<sup>1</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,2,3</sup>',
    affiliations: [
      'Saw Swee Hock School of Public Health, National University of Singapore',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
    ],
    correspondence: 'Saima Hilal, Saw Swee Hock School of Public Health, NUS. Email: saimahilal@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'Neuroinflammation may contribute to cognitive impairment and dementia. IL-6 and IL-8 are linked to neuroinflammatory processes and reduced cognitive function.' },
      { h: 'OBJECTIVE', t: 'To examine baseline IL-6 and IL-8 relationships with cognitive function and five-year cognitive decline in 387 memory clinic patients.' },
      { h: 'RESULTS', t: 'IL-8 was associated with worse cognition especially in attention, executive function, and visuospatial function. No significant association was found for IL-6.' },
      { h: 'CONCLUSION', t: 'Blood inflammatory biomarkers may be useful indicators in identifying patients at risk of cognitive impairment in memory clinic populations.' },
    ],
    keywords: 'blood biomarker, cognitive decline, inflammation, interleukin-6, interleukin-8, memory clinic',
  },
  {
    color: '#3a6b3a',
    journal: 'Current Alzheimer Research',
    jsub: 'BENTHAM SCIENCE',
    doi: '10.2174/1567205018666210820125543',
    volume: 'Curr Alzheimer Res. 2021;18(5):399-413',
    received: '12 January 2021', revised: '20 April 2021', accepted: '10 May 2021',
    title: 'Cerebral Microbleeds and White Matter Hyperintensities are Associated with Cognitive Decline in an Asian Memory Clinic Study',
    authors: 'Bibek Gyanwali<sup>1,2</sup> &nbsp;|&nbsp; Benedict Lui<sup>1</sup> &nbsp;|&nbsp; Chuen S Tan<sup>2</sup> &nbsp;|&nbsp; Eddie J Y Chong<sup>1,3</sup> &nbsp;|&nbsp; Henri Vrooman<sup>4</sup> &nbsp;|&nbsp; Christopher Chen<sup>1,3</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,2,3</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Saw Swee Hock School of Public Health, National University of Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Department of Radiology and Nuclear Medicine, Erasmus University Medical Centre, Netherlands',
    ],
    correspondence: 'Saima Hilal, Saw Swee Hock School of Public Health, NUS. Email: saimahilal@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'Cerebral Small Vessel Disease manifestations including lacunes, microbleeds, and white matter changes contribute to cognitive impairment.' },
      { h: 'METHODS', t: '428 participants underwent baseline MRI and at least three neuropsychological assessments over four years.' },
      { h: 'RESULTS', t: 'Baseline microbleed burden correlated with declines in global cognition, executive function, and memory. Strictly lobar CMBs, as well as WMH volume in anterior and posterior regions, were associated with cognitive decline.' },
      { h: 'CONCLUSION', t: 'Location-specific cerebral small vessel disease markers predict domain-specific cognitive decline and should inform monitoring strategies.' },
    ],
    keywords: 'cerebral small vessel disease, cognitive decline, memory clinic, mixed-location, strictly deep, strictly lobar',
  },
  {
    color: '#c62828',
    journal: 'Stroke',
    jsub: 'AHA / ASA',
    doi: '10.1161/STROKEAHA.115.010700',
    volume: 'Stroke. 2015;46(10):2808-2814',
    received: '12 February 2015', revised: '1 June 2015', accepted: '15 June 2015',
    title: 'Association of Magnetic Resonance Imaging Markers of Cerebrovascular Disease Burden and Cognition',
    authors: 'Xin Xu<sup>1,2</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,2,3</sup> &nbsp;|&nbsp; Simon L Collinson<sup>4</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>1,2</sup> &nbsp;|&nbsp; Mohammad Kamran Ikram<sup>5</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>6</sup> &nbsp;|&nbsp; Christopher Li-Hsian Chen<sup>1,2</sup>',
    affiliations: [
      'Department of Pharmacology, Yong Loo Lin School of Medicine, National University of Singapore',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Saw Swee Hock School of Public Health, National University of Singapore',
      'Department of Psychology, National University of Singapore',
      'Duke-NUS Graduate Medical School, Singapore',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
    ],
    correspondence: 'Christopher Chen, Department of Pharmacology, NUS. Email: phccclh@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND AND PURPOSE', t: 'The study examined associations between cerebrovascular disease burden using multimodal MRI and cognitive function.' },
      { h: 'METHODS', t: '305 cognitively impaired patients and 94 controls underwent neuropsychological testing and brain MRI. A weighted CeVD burden score was computed.' },
      { h: 'RESULTS', t: 'A graded association of CeVD burden with neurocognitive function was found. White matter hyperintensities associated with global deficits; microbleeds with domain-specific impairments.' },
      { h: 'CONCLUSIONS', t: 'Weighted cerebrovascular disease burden score comprising both small- and large-vessel disease markers associated with global and domain-specific cognitive deficits.' },
    ],
    keywords: 'cerebrovascular disorders, cognition, magnetic resonance imaging, stroke',
  },
];

const PAPERS_AI = [
  {
    color: '#006e45',
    journal: 'GeroScience',
    jsub: 'SPRINGER',
    doi: '10.1007/s11357-026-02199-7',
    volume: 'GeroScience. 2026',
    received: '15 October 2025', revised: '10 January 2026', accepted: '20 January 2026',
    title: 'Associations between cognitive frailty and circulating cardiovascular biomarkers in a memory clinic cohort',
    authors: 'Xin Tong Tan<sup>1</sup> &nbsp;|&nbsp; Joyce R Chong<sup>1</sup> &nbsp;|&nbsp; Eddie J Y Chong<sup>1,2</sup> &nbsp;|&nbsp; Ming Ann Sim<sup>1</sup> &nbsp;|&nbsp; Jiangbo Cui<sup>1,3</sup> &nbsp;|&nbsp; Siew Pang Chan<sup>4</sup> &nbsp;|&nbsp; Oi Wah Liew<sup>4</sup> &nbsp;|&nbsp; Boon Yeow Tan<sup>5</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>6</sup> &nbsp;|&nbsp; Arthur Mark Richards<sup>4</sup> &nbsp;|&nbsp; Mitchell K P Lai<sup>1,2</sup> &nbsp;|&nbsp; Christopher Li-Hsian Chen<sup>1,2</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Department of Psychological Medicine, Yong Loo Lin School of Medicine, NUS',
      'Department of Medicine, Yong Loo Lin School of Medicine, NUS',
      "St. Luke's Hospital, Singapore",
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
    ],
    correspondence: 'Christopher Chen, Department of Pharmacology, NUS. Email: phccclh@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'Whether cognitive frailty, characterized by coexisting physical frailty and mild cognitive impairment, correlates with cardiac dysfunction markers remains unclear.' },
      { h: 'METHODS', t: '303 memory clinic participants were assessed with frailty measures and cardiovascular biomarkers including NT-proBNP, GDF-15, and hs-cTnT.' },
      { h: 'RESULTS', t: 'Those with cognitive frailty demonstrated higher NT-proBNP, GDF-15, and hs-cTnT levels. Cognitive frailty predicted accelerated cognitive decline over five years, with elevated NT-proBNP intensifying this decline.' },
      { h: 'CONCLUSIONS', t: 'Cardiovascular pathways warrant investigation as intervention targets for cognitive frailty, bridging cardiac and neurocognitive aging research.' },
    ],
    keywords: 'cognitive frailty, frailty, GDF-15, high-sensitivity cardiac troponin T, mild cognitive impairment, NT-proBNP',
  },
  {
    color: '#7d2035',
    journal: "Alzheimer's & Dementia",
    jsub: "THE JOURNAL OF THE ALZHEIMER'S ASSOCIATION",
    doi: '10.1002/alz.14601',
    volume: "Alzheimers Dement. 2025;21(3):e14601",
    received: '5 September 2024', revised: '15 November 2024', accepted: '2 December 2024',
    title: 'A deep-learning retinal aging biomarker for cognitive decline and incident dementia',
    authors: 'Ming Ann Sim<sup>1,2</sup> &nbsp;|&nbsp; Yih Chung Tham<sup>3</sup> &nbsp;|&nbsp; Simon Nusinovici<sup>3</sup> &nbsp;|&nbsp; Ten Cheer Quek<sup>3</sup> &nbsp;|&nbsp; Marco Yu<sup>3</sup> &nbsp;|&nbsp; Can Can Xue<sup>3</sup> &nbsp;|&nbsp; Miao Li Chee<sup>3</sup> &nbsp;|&nbsp; Qing Sheng Peng<sup>3</sup> &nbsp;|&nbsp; Eugene S J Tan<sup>1,4</sup> &nbsp;|&nbsp; Siew Pang Chan<sup>5</sup> &nbsp;|&nbsp; Yuan Cai<sup>1</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>1,2</sup> &nbsp;|&nbsp; Boon Yeow Tan<sup>6</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>7</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,2,8</sup> &nbsp;|&nbsp; Mitchell K P Lai<sup>1,2</sup> &nbsp;|&nbsp; Hyungwon Choi<sup>9</sup> &nbsp;|&nbsp; Arthur Mark Richards<sup>5</sup> &nbsp;|&nbsp; Ching-Yu Cheng<sup>3</sup> &nbsp;|&nbsp; Christopher L H Chen<sup>1,2</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Singapore Eye Research Institute, Singapore National Eye Centre',
      'National University Heart Centre Singapore',
      'Department of Medicine, Yong Loo Lin School of Medicine, NUS',
      "St. Luke's Hospital, Singapore",
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
      'Saw Swee Hock School of Public Health, National University of Singapore',
      'Department of Medicine, Yong Loo Lin School of Medicine, NUS',
    ],
    correspondence: 'Christopher Chen, Department of Pharmacology, NUS. Email: phccclh@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'RetiPhenoAge is a deep learning-derived retinal biological age estimated from fundus photographs, capturing systemic aging.' },
      { h: 'METHODS', t: 'A memory-clinic cohort was followed for 5 years with retinal photography and cognitive assessments. UK Biobank served as an external replication cohort.' },
      { h: 'RESULTS', t: 'Older RetiPhenoAge associated with incident cognitive decline (subdistribution hazard ratio 1.34, p=0.004) and dementia (p=0.036). UK Biobank replication confirmed RetiPhenoAge predicted incident dementia. The marker correlated with brain MRI changes and aging-related plasma proteins.' },
      { h: 'CONCLUSIONS', t: 'Retinal photography is a non-invasive window into systemic brain ageing and a promising tool for dementia risk stratification.' },
    ],
    keywords: 'biomarker, cognitive decline, deep-learning, dementia, prognostic, retinal age, retinal photography',
  },
  {
    color: '#5c6bc0',
    journal: 'Human Brain Mapping',
    jsub: 'WILEY',
    doi: '10.1002/hbm.70276',
    volume: 'Hum Brain Mapp. 2025;46(12):e70276',
    received: '20 February 2025', revised: '25 June 2025', accepted: '10 July 2025',
    title: 'Mind the Gap: Does Brain Age Improve Alzheimer\'s Disease Prediction?',
    authors: 'Trevor Wei Kiat Tan<sup>1</sup> &nbsp;|&nbsp; Kim-Ngan Nguyen<sup>1</sup> &nbsp;|&nbsp; Chen Zhang<sup>1</sup> &nbsp;|&nbsp; Ru Kong<sup>1</sup> &nbsp;|&nbsp; Susan F Cheng<sup>1</sup> &nbsp;|&nbsp; Fang Ji<sup>2</sup> &nbsp;|&nbsp; Joanna Su Xian Chong<sup>2,3</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>2,3</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>4</sup> &nbsp;|&nbsp; Csaba Orban<sup>1</sup> &nbsp;|&nbsp; Michael W L Chee<sup>5</sup> &nbsp;|&nbsp; Christopher Chen<sup>2,3</sup> &nbsp;|&nbsp; Juan Helen Zhou<sup>2,5</sup> &nbsp;|&nbsp; B T Thomas Yeo<sup>1</sup>',
    affiliations: [
      'Department of Electrical and Computer Engineering, National University of Singapore',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
      'Centre for Sleep and Cognition, National University of Singapore',
    ],
    correspondence: 'B T Thomas Yeo, NUS. Email: thomas.yeo@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'The brain age gap may provide incremental predictive value for Alzheimer\'s disease conversion beyond established biomarkers.' },
      { h: 'METHODS', t: 'Large-scale brain age models trained on 53,542 participants were compared with direct predictive approaches across multiple datasets.' },
      { h: 'RESULTS', t: 'Summarizing brain age with a single scalar (brain age gap) led to poor prediction performance. While higher-dimensional features improved results, direct predictive models still demonstrated superior performance.' },
      { h: 'CONCLUSIONS', t: 'Using chronological age as a pretraining target might be suboptimal for predicting specific health outcomes; task-specific models are preferable.' },
    ],
    keywords: 'brain age, Alzheimers disease, neuroimaging, prediction, machine learning',
  },
  {
    color: '#be0000',
    journal: 'Brain Communications',
    jsub: 'OXFORD UNIVERSITY PRESS',
    doi: '10.1093/braincomms/fcaf413',
    volume: 'Brain Commun. 2025;7(6):fcaf413',
    received: '10 February 2025', revised: '20 June 2025', accepted: '5 July 2025',
    title: 'U-shaped association of resting heart rate with cognitive decline',
    authors: 'Eugene S J Tan<sup>1,2</sup> &nbsp;|&nbsp; Ming Ann Sim<sup>1</sup> &nbsp;|&nbsp; Lucia Li<sup>3</sup> &nbsp;|&nbsp; Anqi Toh<sup>1</sup> &nbsp;|&nbsp; Eddie J Y Chong<sup>1,4</sup> &nbsp;|&nbsp; Siew Pang Chan<sup>5</sup> &nbsp;|&nbsp; Cheuk Ni Kan<sup>1</sup> &nbsp;|&nbsp; Xin Tong Tan<sup>1</sup> &nbsp;|&nbsp; Jiangbo Cui<sup>1</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,4,6</sup> &nbsp;|&nbsp; Joyce R Chong<sup>1</sup> &nbsp;|&nbsp; Mitchell K P Lai<sup>1,4</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>7</sup> &nbsp;|&nbsp; Boon Yeow Tan<sup>8</sup> &nbsp;|&nbsp; A Mark Richards<sup>5</sup> &nbsp;|&nbsp; Lieng-Hsi Ling<sup>5</sup> &nbsp;|&nbsp; Christopher L H Chen<sup>1,4</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'National University Heart Centre Singapore',
      'Imperial College London, United Kingdom',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Department of Medicine, Yong Loo Lin School of Medicine, NUS',
      'Saw Swee Hock School of Public Health, National University of Singapore',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
      "St. Luke's Hospital, Singapore",
    ],
    correspondence: 'Christopher Chen, Department of Pharmacology, NUS. Email: phccclh@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'Both low and high resting heart rates may be associated with adverse cognitive outcomes through distinct neurobiological mechanisms.' },
      { h: 'METHODS', t: '643 memory clinic participants (mean age 72.8 years, 57% female) were followed for five years with neuropsychological and neuroimaging assessments.' },
      { h: 'RESULTS', t: 'U-shaped association with cognitive impairment was observed. Bradycardia correlated with reduced grey matter and elevated biomarkers (pTau-181, neurofilament light chain), while elevated rates showed increased cerebrovascular lesions.' },
      { h: 'CONCLUSIONS', t: 'Heart rate extremes impact cognition through distinct neurobiological mechanisms, with implications for cardiovascular monitoring in older adults.' },
    ],
    keywords: 'biomarkers, bradycardia, cerebrovascular disease, cognitive decline, heart rate',
  },
  {
    color: '#336699',
    journal: 'Brain Communications',
    jsub: 'OXFORD UNIVERSITY PRESS',
    doi: '10.1093/braincomms/fcad192',
    volume: 'Brain Commun. 2023;5(4):fcad192',
    received: '12 January 2023', revised: '30 May 2023', accepted: '18 June 2023',
    title: 'Longitudinal associations between \u03b2-amyloid and cortical thickness in mild cognitive impairment',
    authors: 'Elijah Mak<sup>1</sup> &nbsp;|&nbsp; Liwen Zhang<sup>2</sup> &nbsp;|&nbsp; Chin Hong Tan<sup>3</sup> &nbsp;|&nbsp; Anthonin Reilhac<sup>4</sup> &nbsp;|&nbsp; Hee Youn Shim<sup>2</sup> &nbsp;|&nbsp; Marcus Ong Qin Wen<sup>2</sup> &nbsp;|&nbsp; Zi Xuen Wong<sup>2</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>2,5</sup> &nbsp;|&nbsp; Xin Xu<sup>2,5</sup> &nbsp;|&nbsp; Mary Stephenson<sup>6</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>7</sup> &nbsp;|&nbsp; Juan Helen Zhou<sup>2,8</sup> &nbsp;|&nbsp; John T O\'Brien<sup>1</sup> &nbsp;|&nbsp; Christopher Li-Hsian Chen<sup>2,5</sup>',
    affiliations: [
      'Department of Psychiatry, University of Cambridge, United Kingdom',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'National University of Singapore',
      'Bioinformatics Institute, Agency for Science Technology and Research (A*STAR), Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Singapore BioImaging Consortium, A*STAR, Singapore',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
      'Centre for Sleep and Cognition, National University of Singapore',
    ],
    correspondence: 'Christopher Chen, Department of Pharmacology, NUS. Email: phccclh@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'How beta-amyloid accumulation influences regional brain atrophy in Alzheimer\'s disease is not fully understood.' },
      { h: 'METHODS', t: '45 MCI patients and 12 controls underwent PET imaging and structural MRI over approximately 24 months.' },
      { h: 'RESULTS', t: 'Regional amyloid in the right banks of the superior temporal sulcus was associated with longitudinal cortical thinning in the right medial orbitofrontal cortex among MCI patients, correlating with memory decline.' },
      { h: 'CONCLUSIONS', t: 'Findings indicate an increasing influence of amyloid on neurodegeneration across the disease spectrum, supporting amyloid-targeted intervention in the MCI stage.' },
    ],
    keywords: '[11C]-PiB PET, cortical thickness, longitudinal cortical thinning, mild cognitive impairment, regional beta-amyloid',
  },
  {
    color: '#006064',
    journal: 'Journal of Cerebral Blood Flow & Metabolism',
    jsub: 'SAGE / ISCBFM',
    doi: '10.1177/0271678X20902187',
    volume: 'J Cereb Blood Flow Metab. 2021;41(1):105-115',
    received: '20 June 2019', revised: '18 November 2019', accepted: '5 December 2019',
    title: 'Cerebral microinfarcts affect brain structural network topology in cognitively impaired patients',
    authors: 'Liwen Zhang<sup>1</sup> &nbsp;|&nbsp; Geert Jan Biessels<sup>2</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,3,4</sup> &nbsp;|&nbsp; Joanna Su Xian Chong<sup>1,5</sup> &nbsp;|&nbsp; Siwei Liu<sup>6</sup> &nbsp;|&nbsp; Hee Youn Shim<sup>1</sup> &nbsp;|&nbsp; Xin Xu<sup>1,3</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>1,3</sup> &nbsp;|&nbsp; Zi Xuen Wong<sup>1</sup> &nbsp;|&nbsp; Yng Miin Loke<sup>1</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>7</sup> &nbsp;|&nbsp; Tan Boon Yeow<sup>8</sup> &nbsp;|&nbsp; Christopher Li-Hsian Chen<sup>1,3</sup> &nbsp;|&nbsp; Juan Helen Zhou<sup>1,5</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'UMC Utrecht Brain Center, University Medical Center Utrecht, Netherlands',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Saw Swee Hock School of Public Health, National University of Singapore',
      'Centre for Sleep and Cognition, National University of Singapore',
      'Bioinformatics Institute, Agency for Science Technology and Research (A*STAR), Singapore',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
      "St. Luke's Hospital, Singapore",
    ],
    correspondence: 'Juan Helen Zhou, National University of Singapore. Email: helen.zhou@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'Cerebral microinfarcts are associated with cognitive impairment, but their impact on large-scale brain network topology remains unclear.' },
      { h: 'METHODS', t: 'Brain imaging data from 92 Alzheimer\'s disease patients and 110 individuals with cognitive impairment but no dementia were analyzed.' },
      { h: 'RESULTS', t: 'Those with cortical-CMIs demonstrated lower efficiency and degree centrality in executive control and dorsal attention networks in CIND and reduced network clustering in AD. Disrupted structural connectivity mediated associations between cortical-CMIs and visuoconstruction difficulties.' },
      { h: 'CONCLUSIONS', t: 'First in vivo human evidence that cortical-CMIs impair cognition via disrupting structural connectivity, opening pathways for network-targeted interventions.' },
    ],
    keywords: 'Alzheimers disease, cognitive impairment, cortical cerebral microinfarcts, structural network topology',
  },
  {
    color: '#e65100',
    journal: 'Scientific Reports',
    jsub: 'NATURE PORTFOLIO',
    doi: '10.1038/s41598-020-63540-4',
    volume: 'Sci Rep. 2020;10(1):6457',
    received: '5 November 2019', revised: '10 March 2020', accepted: '27 March 2020',
    title: 'Distinct BOLD variability changes in the default mode and salience networks in Alzheimer\'s disease spectrum and associations with cognitive decline',
    authors: 'Liwen Zhang<sup>1</sup> &nbsp;|&nbsp; Xi-Nian Zuo<sup>2</sup> &nbsp;|&nbsp; Kwun Kei Ng<sup>1</sup> &nbsp;|&nbsp; Joanna Su Xian Chong<sup>1,3</sup> &nbsp;|&nbsp; Hee Youn Shim<sup>1</sup> &nbsp;|&nbsp; Marcus Qin Wen Ong<sup>1</sup> &nbsp;|&nbsp; Yng Miin Loke<sup>1</sup> &nbsp;|&nbsp; Boon Linn Choo<sup>1</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>1,3</sup> &nbsp;|&nbsp; Zi Xuen Wong<sup>1</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,3,4</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>5</sup> &nbsp;|&nbsp; Boon Yeow Tan<sup>6</sup> &nbsp;|&nbsp; Christopher Li-Hsian Chen<sup>1,3</sup> &nbsp;|&nbsp; Juan Helen Zhou<sup>1,7</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Beijing Normal University, China',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Saw Swee Hock School of Public Health, National University of Singapore',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
      "St. Luke's Hospital, Singapore",
      'Centre for Sleep and Cognition, National University of Singapore',
    ],
    correspondence: 'Juan Helen Zhou, National University of Singapore. Email: helen.zhou@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'BOLD signal variability in resting-state fMRI may capture neural dynamics beyond mean connectivity, reflecting brain flexibility across states.' },
      { h: 'METHODS', t: 'Brain imaging data from 96 individuals with Alzheimer\'s disease, 98 with mild cognitive impairment, and 48 healthy controls were analyzed at different frequency bands.' },
      { h: 'RESULTS', t: 'Reciprocal patterns were found between default mode and salience networks during the mild impairment stage. Decreased variability in the posterior default mode network correlated with poorer baseline cognition, smaller hippocampus, and predicted faster cognitive decline.' },
      { h: 'CONCLUSIONS', t: 'BOLD variability is a sensitive and dynamic marker for neural changes across the Alzheimer\'s disease continuum.' },
    ],
    keywords: 'BOLD variability, default mode network, salience network, Alzheimers disease, fMRI, cognitive decline',
  },
  {
    color: '#4e342e',
    journal: 'Human Brain Mapping',
    jsub: 'WILEY',
    doi: '10.1002/hbm.24928',
    volume: 'Hum Brain Mapp. 2020;41(8):2037-2047',
    received: '15 May 2019', revised: '3 September 2019', accepted: '18 September 2019',
    title: 'Longitudinal trajectory of Amyloid-related hippocampal subfield atrophy in nondemented elderly',
    authors: 'Liwen Zhang<sup>1</sup> &nbsp;|&nbsp; Elijah Mak<sup>2</sup> &nbsp;|&nbsp; Anthonin Reilhac<sup>3</sup> &nbsp;|&nbsp; Hee Y Shim<sup>1</sup> &nbsp;|&nbsp; Kwun K Ng<sup>1</sup> &nbsp;|&nbsp; Marcus Q W Ong<sup>1</sup> &nbsp;|&nbsp; Fang Ji<sup>1</sup> &nbsp;|&nbsp; Eddie J Y Chong<sup>1,4</sup> &nbsp;|&nbsp; Xin Xu<sup>1,4</sup> &nbsp;|&nbsp; Zi X Wong<sup>1</sup> &nbsp;|&nbsp; Mary C Stephenson<sup>5</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>6</sup> &nbsp;|&nbsp; Boon Y Tan<sup>7</sup> &nbsp;|&nbsp; John T O\'Brien<sup>2</sup> &nbsp;|&nbsp; Juan H Zhou<sup>1,8</sup> &nbsp;|&nbsp; Christopher L H Chen<sup>1,4</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Psychiatry, University of Cambridge, United Kingdom',
      'Bioinformatics Institute, Agency for Science Technology and Research (A*STAR), Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Singapore BioImaging Consortium, A*STAR, Singapore',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
      "St. Luke's Hospital, Singapore",
      'Centre for Sleep and Cognition, National University of Singapore',
    ],
    correspondence: 'Christopher Chen, Department of Pharmacology, NUS. Email: phccclh@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'Hippocampal subfield atrophy may precede clinical dementia and track amyloid pathology, potentially serving as a sensitive biomarker.' },
      { h: 'METHODS', t: 'Two independent longitudinal datasets with PET imaging and advanced MRI segmentation were analyzed at multiple timepoints.' },
      { h: 'RESULTS', t: 'Higher amyloid-beta correlated with faster CA1 volume decline in cognitively normal individuals. This pattern expanded across multiple hippocampal subfields in mild cognitive impairment, correlating with memory loss.' },
      { h: 'CONCLUSIONS', t: 'Hippocampal subfield volumetry is sensitive to amyloid-related neurodegeneration in the preclinical stage and could inform early intervention trials.' },
    ],
    keywords: 'hippocampal subfield atrophy, longitudinal atrophy trajectory, nondemented elderly, beta-amyloid',
  },
];

const PAPERS_STROKE = [
  {
    color: '#d45000',
    journal: 'Neurology',
    jsub: 'AMERICAN ACADEMY OF NEUROLOGY',
    doi: '10.1212/WNL.0000000000214574',
    volume: 'Neurology. 2026;106(3):e214574',
    received: '1 August 2025', revised: '5 October 2025', accepted: '20 October 2025',
    title: 'Development of a Prognostic Model for Poststroke Dementia Using Multiple International Cohorts: A STROKOG Collaboration Study',
    authors: 'Jessica W Lo<sup>1</sup> &nbsp;|&nbsp; John D Crawford<sup>1</sup> &nbsp;|&nbsp; David W Desmond<sup>2</sup> &nbsp;|&nbsp; Olivier Godefroy<sup>3</sup> &nbsp;|&nbsp; Martine Roussel<sup>3</sup> &nbsp;|&nbsp; R\u00e9gis Bordet<sup>4</sup> &nbsp;|&nbsp; Hee-Joon Bae<sup>5</sup> &nbsp;|&nbsp; Jae-Sung Lim<sup>5</sup> &nbsp;|&nbsp; Christopher P L H Chen<sup>6</sup> &nbsp;|&nbsp; Eddie J Chong<sup>6</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>7</sup> &nbsp;|&nbsp; Henry Brodaty<sup>1</sup> &nbsp;|&nbsp; Perminder S Sachdev<sup>1</sup>',
    affiliations: [
      'Centre for Healthy Brain Ageing, University of New South Wales, Sydney, Australia',
      'Department of Neurology, Columbia University, New York, USA',
      'University Hospital Amiens, Amiens, France',
      'University of Lille, Lille, France',
      'Seoul National University Bundang Hospital, Seoul, South Korea',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
    ],
    correspondence: 'John D Crawford, CHeBA, UNSW Sydney. Email: j.crawford@unsw.edu.au',
    abstract: [
      { h: 'OBJECTIVE', t: 'Poststroke dementia is a major consequence of stroke, yet validated prognostic models remain lacking across diverse populations.' },
      { h: 'METHODS', t: 'Individual participant data from 12 international cohort studies (n=2,663 stroke survivors, mean age 67.0) were pooled and analyzed.' },
      { h: 'RESULTS', t: 'The model incorporating age, sex, education, history of previous stroke, diabetes, and stroke severity generalized well to recent and European cohorts, though risks were somewhat overestimated in Asian populations.' },
      { h: 'CONCLUSIONS', t: 'This internationally validated prognostic model enables clinical risk stratification for post-stroke cognitive decline across diverse settings.' },
    ],
    keywords: 'poststroke dementia, prognostic model, STROKOG, stroke, risk stratification',
  },
  {
    color: '#d45000',
    journal: 'Neurology',
    jsub: 'AMERICAN ACADEMY OF NEUROLOGY',
    doi: '10.1212/WNL.0000000000207281',
    volume: 'Neurology. 2023;100(23):e2331-e2341',
    received: '10 September 2022', revised: '5 January 2023', accepted: '20 January 2023',
    title: 'Short-term Trajectories of Poststroke Cognitive Function: A STROKOG Collaboration Study',
    authors: 'Jessica W Lo<sup>1</sup> &nbsp;|&nbsp; John D Crawford<sup>1</sup> &nbsp;|&nbsp; David W Desmond<sup>2</sup> &nbsp;|&nbsp; Hee-Joon Bae<sup>3</sup> &nbsp;|&nbsp; Jae-Sung Lim<sup>3</sup> &nbsp;|&nbsp; Olivier Godefroy<sup>4</sup> &nbsp;|&nbsp; Martine Roussel<sup>4</sup> &nbsp;|&nbsp; Sebastian K\u00f6hler<sup>5</sup> &nbsp;|&nbsp; Julie Staals<sup>5</sup> &nbsp;|&nbsp; Frans Verhey<sup>5</sup> &nbsp;|&nbsp; Christopher Chen<sup>6</sup> &nbsp;|&nbsp; Xin Xu<sup>6</sup> &nbsp;|&nbsp; Eddie J Chong<sup>6</sup> &nbsp;|&nbsp; Nagaendran Kandiah<sup>7</sup> &nbsp;|&nbsp; R\u00e9gis Bordet<sup>8</sup> &nbsp;|&nbsp; Henry Brodaty<sup>1</sup> &nbsp;|&nbsp; Perminder S Sachdev<sup>1</sup>',
    affiliations: [
      'Centre for Healthy Brain Ageing, University of New South Wales, Sydney, Australia',
      'Department of Neurology, Columbia University, New York, USA',
      'Seoul National University Bundang Hospital, Seoul, South Korea',
      'University Hospital Amiens, Amiens, France',
      'Maastricht University, Maastricht, Netherlands',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'National Neuroscience Institute, Singapore',
      'University of Lille, Lille, France',
    ],
    correspondence: 'Jessica W Lo, CHeBA, UNSW Sydney. Email: jessica.lo@unsw.edu.au',
    abstract: [
      { h: 'OBJECTIVE', t: 'This study characterised the short-term trajectory of cognitive recovery in the first 12 months following stroke.' },
      { h: 'METHODS', t: 'Latent class growth analysis on data from nine hospital-based cohorts (n=1,149 participants) identified distinct cognitive trajectory subgroups.' },
      { h: 'RESULTS', t: 'Three distinct cognitive trajectory groups were identified. Risk factors for poorer outcomes included advanced age, limited education, diabetes, large vessel stroke, and greater stroke severity.' },
      { h: 'CONCLUSIONS', t: 'Short-term cognitive trajectory patterns help clinicians identify patients at risk of poor long-term outcomes following stroke.' },
    ],
    keywords: 'poststroke cognition, cognitive recovery, STROKOG, stroke, trajectory',
  },
  {
    color: '#c62828',
    journal: 'Stroke',
    jsub: 'AHA / ASA',
    doi: '10.1161/STROKEAHA.121.035796',
    volume: 'Stroke. 2022;53(4):1318-1327',
    received: '15 May 2021', revised: '8 September 2021', accepted: '22 September 2021',
    title: 'Long-Term Cognitive Decline After Stroke: An Individual Participant Data Meta-Analysis',
    authors: 'Jessica W Lo<sup>1</sup> &nbsp;|&nbsp; John D Crawford<sup>1</sup> &nbsp;|&nbsp; David W Desmond<sup>2</sup> &nbsp;|&nbsp; Hee-Joon Bae<sup>3</sup> &nbsp;|&nbsp; Jae-Sung Lim<sup>3</sup> &nbsp;|&nbsp; Olivier Godefroy<sup>4</sup> &nbsp;|&nbsp; Martine Roussel<sup>4</sup> &nbsp;|&nbsp; Yeonwook Kang<sup>5</sup> &nbsp;|&nbsp; Sebastian K\u00f6hler<sup>6</sup> &nbsp;|&nbsp; Christopher Chen<sup>7</sup> &nbsp;|&nbsp; Xin Xu<sup>7</sup> &nbsp;|&nbsp; Eddie J Chong<sup>7</sup> &nbsp;|&nbsp; Nagaendran Kandiah<sup>8</sup> &nbsp;|&nbsp; Henry Brodaty<sup>1</sup> &nbsp;|&nbsp; Perminder S Sachdev<sup>1</sup>',
    affiliations: [
      'Centre for Healthy Brain Ageing, University of New South Wales, Sydney, Australia',
      'Department of Neurology, Columbia University, New York, USA',
      'Seoul National University Bundang Hospital, Seoul, South Korea',
      'University Hospital Amiens, Amiens, France',
      'Hallym University, South Korea',
      'Maastricht University, Maastricht, Netherlands',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'National Neuroscience Institute, Singapore',
    ],
    correspondence: 'Perminder S Sachdev, CHeBA, UNSW Sydney. Email: p.sachdev@unsw.edu.au',
    abstract: [
      { h: 'OBJECTIVE', t: 'This IPD meta-analysis synthesised long-term cognitive trajectories from stroke survivors across multiple international cohorts.' },
      { h: 'METHODS', t: '1,488 patients (mean age 66.3 years) were followed for a median 2.68 years with repeated cognitive assessments.' },
      { h: 'RESULTS', t: 'After an initial period of improvement through up to 1-year poststroke, decline was seen in global cognition and all domains. Decline was significantly faster in patients with stroke compared with controls. Older age and recurrent stroke accelerated cognitive deterioration.' },
      { h: 'CONCLUSIONS', t: 'Post-stroke cognitive decline occurs after initial recovery, highlighting the need for long-term cognitive monitoring in stroke survivors.' },
    ],
    keywords: 'cognition, cognitive dysfunction, meta-analysis, risk factors, stroke',
  },
  {
    color: '#880e4f',
    journal: "Journal of Alzheimer's Disease",
    jsub: 'IOS PRESS',
    doi: '10.3233/JAD-210619',
    volume: 'J Alzheimers Dis. 2021;83(2):557-568',
    received: '20 April 2021', revised: '5 June 2021', accepted: '20 June 2021',
    title: 'Domain-Specific Cognitive Trajectories Among Patients with Minor Stroke or Transient Ischemic Attack in a 6-Year Prospective Asian Cohort: Serial Patterns and Indicators',
    authors: 'Xuhao Zhao<sup>1</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>2,3</sup> &nbsp;|&nbsp; Wei Qi<sup>1</sup> &nbsp;|&nbsp; Ting Pang<sup>2</sup> &nbsp;|&nbsp; Xin Xu<sup>2,3</sup> &nbsp;|&nbsp; Christopher Chen<sup>2,3</sup>',
    affiliations: [
      'Zhejiang University, Hangzhou, China',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
    ],
    correspondence: 'Christopher Chen, Department of Pharmacology, NUS. Email: phccclh@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'Cognitive trajectories after minor stroke/TIA remain poorly characterised beyond global cognition measures.' },
      { h: 'METHODS', t: '244 patients were followed for six years with domain-specific neuropsychological assessments at multiple timepoints.' },
      { h: 'RESULTS', t: 'PSCI prevalence ranged from 34.6–53.7%, with a 21.9% incidence rate. Visual memory showed significant improvement, while other domains remained stable. Short-term cognitive improvement could be an early indicator of long-term cognitive trajectory.' },
      { h: 'CONCLUSIONS', t: 'Minor stroke/TIA patients show selective cognitive vulnerability, warranting domain-specific monitoring and targeted rehabilitation.' },
    ],
    keywords: 'cognitive impairment, cognitive trajectory, domain-specific cognition, minor stroke, transient ischemic attack',
  },
  {
    color: '#1565c0',
    journal: 'Neurology',
    jsub: 'AMERICAN ACADEMY OF NEUROLOGY',
    doi: '10.1212/WNL.0000000000008612',
    volume: 'Neurology. 2019;93(24):e2257-e2271',
    received: '5 February 2019', revised: '10 June 2019', accepted: '25 June 2019',
    title: 'Profile of and risk factors for poststroke cognitive impairment in diverse ethnoregional groups',
    authors: 'Jessica W Lo<sup>1</sup> &nbsp;|&nbsp; John D Crawford<sup>1</sup> &nbsp;|&nbsp; David W Desmond<sup>2</sup> &nbsp;|&nbsp; Olivier Godefroy<sup>3</sup> &nbsp;|&nbsp; Hanna Jokinen<sup>4</sup> &nbsp;|&nbsp; Simin Mahinrad<sup>5</sup> &nbsp;|&nbsp; Hee-Joon Bae<sup>6</sup> &nbsp;|&nbsp; Jae-Sung Lim<sup>6</sup> &nbsp;|&nbsp; Sebastian K\u00f6hler<sup>7</sup> &nbsp;|&nbsp; Christopher Chen<sup>8</sup> &nbsp;|&nbsp; Xin Xu<sup>8</sup> &nbsp;|&nbsp; Eddie J Chong<sup>8</sup> &nbsp;|&nbsp; Henry Brodaty<sup>1</sup> &nbsp;|&nbsp; Perminder S Sachdev<sup>1</sup>',
    affiliations: [
      'Centre for Healthy Brain Ageing, University of New South Wales, Sydney, Australia',
      'Department of Neurology, Columbia University, New York, USA',
      'University Hospital Amiens, Amiens, France',
      'Helsinki University Hospital, Helsinki, Finland',
      'Leiden University Medical Center, Leiden, Netherlands',
      'Seoul National University Bundang Hospital, Seoul, South Korea',
      'Maastricht University, Maastricht, Netherlands',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
    ],
    correspondence: 'Perminder S Sachdev, CHeBA, UNSW Sydney. Email: p.sachdev@unsw.edu.au',
    abstract: [
      { h: 'OBJECTIVE', t: 'This study examined the profile and risk factors for poststroke cognitive impairment across diverse ethnoregional groups.' },
      { h: 'METHODS', t: 'Individual participant data from international STROKOG cohorts were harmonized and analyzed across ethnoregional groups.' },
      { h: 'RESULTS', t: 'Cognitive impairment profiles varied by ethnoregional group, with education and stroke severity as universal risk factors across all cohorts.' },
      { h: 'CONCLUSIONS', t: 'Ethnoregional context shapes post-stroke cognitive outcomes and should inform culturally adapted monitoring and intervention strategies.' },
    ],
    keywords: 'poststroke cognitive impairment, ethnoregional, risk factors, STROKOG, vascular dementia',
  },
];

const PAPERS_CLINICAL = [
  {
    color: '#2e7d32',
    journal: 'Patient Education and Counseling',
    jsub: 'ELSEVIER',
    doi: '10.1016/j.pec.2025.108797',
    volume: 'Patient Educ Couns. 2025;137:108797',
    received: '1 January 2025', revised: '15 March 2025', accepted: '1 April 2025',
    title: 'Adherence to lifestyle intervention activities in the SINgapore GERiatric to reduce cognitive decline and physical frailty (SINGER) study: A one-year preliminary analysis of process evaluation',
    authors: 'Kwong Hsia Yap<sup>1</sup> &nbsp;|&nbsp; April Ka Sin Phua<sup>1</sup> &nbsp;|&nbsp; Richelle Santiano<sup>1</sup> &nbsp;|&nbsp; Melmar Folloso<sup>1</sup> &nbsp;|&nbsp; Eddie J Y Chong<sup>1,2</sup> &nbsp;|&nbsp; Xin Xu<sup>1,2</sup> &nbsp;|&nbsp; Christiani Jeyakumar Henry<sup>3</sup> &nbsp;|&nbsp; Effie Chew<sup>4</sup> &nbsp;|&nbsp; Andrea B Maier<sup>5</sup> &nbsp;|&nbsp; Nagaendran Kandiah<sup>6</sup> &nbsp;|&nbsp; Christopher Philip Li-Hsian Chen<sup>1,2</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Clinical Nutrition Research Centre, Agency for Science Technology and Research (A*STAR), Singapore',
      'Department of Medicine, Yong Loo Lin School of Medicine, NUS',
      'Department of Medicine and Aged Care, University of Melbourne, Australia',
      'National Neuroscience Institute, Singapore',
    ],
    correspondence: 'Kwong Hsia Yap, Memory Aging and Cognition Centre, NUS. Email: kwh.yap@nus.edu.sg',
    abstract: [
      { h: 'OBJECTIVE', t: 'This process evaluation examined adherence to the multimodal SINGER lifestyle intervention in community-dwelling older Singaporeans.' },
      { h: 'METHODS', t: 'Latent Class Analysis was used to identify distinct participant subgroups over twelve months of the structured intervention.' },
      { h: 'RESULTS', t: 'Over 70% of participants achieving moderate to high adherence. Participants demonstrated stronger engagement with vascular and dietary components versus cognitive activities. Female gender and higher education predicted better adherence.' },
      { h: 'CONCLUSIONS', t: 'Targeted strategies are needed to support subgroups with lower adherence and optimize long-term engagement in multidomain dementia prevention programmes.' },
    ],
    keywords: 'adherence, dementia, multidomain interventions, prevention, process evaluation',
  },
  {
    color: '#00695c',
    journal: 'The Lancet Regional Health \u2013 Western Pacific',
    jsub: 'THE LANCET',
    doi: '10.1016/j.lanwpc.2024.101198',
    volume: 'Lancet Reg Health West Pac. 2024',
    received: '12 March 2024', revised: '20 July 2024', accepted: '5 August 2024',
    title: 'Independent and joint associations of cardiometabolic multimorbidity and depression on cognitive function: findings from multi-regional cohorts and generalisation from community to clinic',
    authors: 'Xuhao Zhao<sup>1</sup> &nbsp;|&nbsp; Xiaolin Xu<sup>1</sup> &nbsp;|&nbsp; Yifan Yan<sup>1</sup> &nbsp;|&nbsp; Darren M Lipnicki<sup>2</sup> &nbsp;|&nbsp; Ting Pang<sup>3</sup> &nbsp;|&nbsp; John D Crawford<sup>2</sup> &nbsp;|&nbsp; Eddie Chong<sup>3</sup> &nbsp;|&nbsp; Christopher Chen<sup>3</sup> &nbsp;|&nbsp; Perminder S Sachdev<sup>2</sup> &nbsp;|&nbsp; Xin Xu<sup>1,3</sup>',
    affiliations: [
      'University of Sydney, Sydney, Australia',
      'Centre for Healthy Brain Ageing, University of New South Wales, Sydney, Australia',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
    ],
    correspondence: 'Xin Xu, University of Sydney. Email: xin.xu@sydney.edu.au',
    abstract: [
      { h: 'BACKGROUND', t: 'Cardiometabolic multimorbidity and depression may synergistically impair cognitive function, but joint effects across diverse cohorts remain understudied.' },
      { h: 'METHODS', t: '30,382 older adults across 14 international cohorts were examined for independent and joint associations of cardiometabolic multimorbidity and depression with cognitive outcomes.' },
      { h: 'RESULTS', t: 'Each of CMM and depression was independently associated with cross-sectional and longitudinal cognitive function. Participants experiencing both conditions demonstrated notably reduced cognitive performance and accelerated cognitive decline.' },
      { h: 'CONCLUSIONS', t: 'Integrated cardiometabolic and mental health management is urgent for global dementia prevention, with synergistic effects underscoring the importance of treating comorbidities together.' },
    ],
    keywords: 'cardiometabolic multimorbidity, depression, cognitive function, dementia prevention, comorbidity',
  },
  {
    color: '#37474f',
    journal: "Journal of Alzheimer's Disease",
    jsub: 'IOS PRESS',
    doi: '10.3233/JAD-220520',
    volume: 'J Alzheimers Dis. 2022;89(4):1323-1330',
    received: '5 April 2022', revised: '22 June 2022', accepted: '10 July 2022',
    title: 'Validation of the Informant Quick Dementia Rating System (QDRS) among Older Adults in Singapore',
    authors: 'Ting Pang<sup>1</sup> &nbsp;|&nbsp; Eddie Jun Yi Chong<sup>1,2</sup> &nbsp;|&nbsp; Zi Xuen Wong<sup>1</sup> &nbsp;|&nbsp; Kimberly Ann Chew<sup>1</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>3</sup> &nbsp;|&nbsp; Christopher Chen<sup>1,2</sup> &nbsp;|&nbsp; Xin Xu<sup>1,2</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
    ],
    correspondence: 'Xin Xu, Department of Pharmacology, NUS. Email: summer.xu@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'Brief cognitive screening tools that informants can administer are needed for early dementia detection in clinical and community settings.' },
      { h: 'OBJECTIVE', t: 'Validity, reliability, and cost-effectiveness of the Quick Dementia Rating System (QDRS) were assessed in 177 Singapore memory clinic participants.' },
      { h: 'RESULTS', t: 'The tool demonstrated excellent internal consistency (Cronbach alpha = 0.939) and high correlations with comparison measures. With optimal cutoff scores, it achieved 85% overall accuracy and could reduce time to identify MCI subjects by 75.3%.' },
      { h: 'CONCLUSION', t: 'The QDRS is a reliable and cost-effective cognitive impairment screening tool suitable for informant-administration in diverse clinical settings.' },
    ],
    keywords: 'cost-effectiveness, Quick Dementia Rating System, discriminant utility, mild cognitive impairment, staging tool',
  },
  {
    color: '#4527a0',
    journal: "Journal of Prevention of Alzheimer's Disease",
    jsub: 'SPRINGER',
    doi: '10.14283/jpad.2022.5',
    volume: 'J Prev Alzheimers Dis. 2022;9(1):40-48',
    received: '8 September 2021', revised: '5 November 2021', accepted: '22 November 2021',
    title: 'The SINgapore GERiatric Intervention Study to Reduce Cognitive Decline and Physical Frailty (SINGER): Study Design and Protocol',
    authors: 'Xin Xu<sup>1,2</sup> &nbsp;|&nbsp; Kimberly A Chew<sup>1</sup> &nbsp;|&nbsp; Zi Xuen Wong<sup>1</sup> &nbsp;|&nbsp; April K S Phua<sup>1</sup> &nbsp;|&nbsp; Eddie J Y Chong<sup>1,2</sup> &nbsp;|&nbsp; Clement K L Teo<sup>1</sup> &nbsp;|&nbsp; Nandini Sathe<sup>3</sup> &nbsp;|&nbsp; Yi Chun Chooi<sup>3</sup> &nbsp;|&nbsp; Wern Pei Fiona Chia<sup>3</sup> &nbsp;|&nbsp; Christiani Jeyakumar Henry<sup>3</sup> &nbsp;|&nbsp; Effie Chew<sup>4</sup> &nbsp;|&nbsp; Min Wang<sup>4</sup> &nbsp;|&nbsp; Andrea B Maier<sup>5</sup> &nbsp;|&nbsp; Nagaendran Kandiah<sup>6</sup> &nbsp;|&nbsp; Christopher Li-Hsian Chen<sup>1,2</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Clinical Nutrition Research Centre, Agency for Science Technology and Research (A*STAR), Singapore',
      'Department of Medicine, Yong Loo Lin School of Medicine, NUS',
      'University of Melbourne, Melbourne, Australia',
      'National Neuroscience Institute, Singapore',
    ],
    correspondence: 'Christopher Chen, Department of Pharmacology, NUS. Email: phccclh@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'SINGER is a multimodal lifestyle intervention trial targeting cognitive decline and physical frailty in older Singaporeans at elevated dementia risk.' },
      { h: 'METHODS', t: 'Two-year RCT of 1,200 adults aged 60–77 comparing Self-Guided versus Structured Lifestyle Intervention including dietary advice, exercise, cognitive training, and vascular risk factors management.' },
      { h: 'PRIMARY OUTCOME', t: 'Global cognition via modified Neuropsychological Battery; secondary outcomes include domain-specific cognition, brain imaging, chronic disease progression, biomarkers, and quality of life.' },
      { h: 'CONCLUSIONS', t: 'SINGER addresses a critical gap in Asian multidomain dementia prevention evidence, informed by the successful FINGER trial design.' },
    ],
    keywords: 'randomized controlled trial, aged, cognitive dysfunction, multi-domain lifestyle interventions',
  },
  {
    color: '#1b5e20',
    journal: 'Age and Ageing',
    jsub: 'OXFORD UNIVERSITY PRESS',
    doi: '10.1093/ageing/afaa276',
    volume: 'Age Ageing. 2021;50(4):1236-1242',
    received: '20 April 2020', revised: '15 August 2020', accepted: '2 September 2020',
    title: 'Vision, vision-specific functioning and mobility, and their relationship with clinically assessed cognitive impairment',
    authors: 'Eva K Fenwick<sup>1</sup> &nbsp;|&nbsp; Alfred T L Gan<sup>1</sup> &nbsp;|&nbsp; Ryan E K Man<sup>1</sup> &nbsp;|&nbsp; Preeti Gupta<sup>1</sup> &nbsp;|&nbsp; Charumathi Sabanayagam<sup>1</sup> &nbsp;|&nbsp; Ching-Yu Cheng<sup>1</sup> &nbsp;|&nbsp; Christopher Li-Hsian Chen<sup>2,3</sup> &nbsp;|&nbsp; Carol Y Cheung<sup>4</sup> &nbsp;|&nbsp; Kah Hie Wong<sup>5</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>5</sup> &nbsp;|&nbsp; Xin Xu<sup>2,3</sup> &nbsp;|&nbsp; Saima Hilal<sup>2,3,6</sup> &nbsp;|&nbsp; Eddie J Y Chong<sup>2,3</sup> &nbsp;|&nbsp; Yih-Chung Tham<sup>1</sup> &nbsp;|&nbsp; Tien Y Wong<sup>1</sup> &nbsp;|&nbsp; Ecosse L Lamoureux<sup>1</sup>',
    affiliations: [
      'Singapore Eye Research Institute, Singapore National Eye Centre, Singapore',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Chinese University of Hong Kong, Hong Kong SAR',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
      'Saw Swee Hock School of Public Health, National University of Singapore',
    ],
    correspondence: 'Ecosse L Lamoureux, Singapore Eye Research Institute. Email: ecosse.lamoureux@seri.com.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'The relationship between self-reported visual disability and cognitive impairment in older individuals is unclear.' },
      { h: 'METHODS', t: '874 adults aged 60+ at higher dementia risk underwent neuropsychological testing and comprehensive vision and mobility assessments.' },
      { h: 'RESULTS', t: 'Worsening vision-specific functioning and mobility significantly increased odds of mild and moderate cognitive impairment. The odds of mild CIND increased significantly with every standard deviation worsening of visual acuity (OR: 1.62).' },
      { h: 'CONCLUSIONS', t: 'Interventions to prevent vision loss and improve quality of life may reduce likelihood of age-related cognitive decline in at-risk older adults.' },
    ],
    keywords: 'cognitive dysfunction, elderly, mobility, self-reported, vision loss, visual acuity, visual functioning',
  },
  {
    color: '#263238',
    journal: "Alzheimer's & Dementia: Translational Research & Clinical Interventions",
    jsub: "WILEY / ALZHEIMER'S ASSOCIATION",
    doi: '10.1002/trc2.12161',
    volume: 'Alzheimers Dement (N Y). 2021;7(1):e12161',
    received: '10 April 2020', revised: '15 July 2020', accepted: '30 July 2020',
    title: 'NEURoaid II (MLC901) in cognitively Impaired not demenTEd patientS (NEURITES): A pilot double blind, placebo-controlled randomized trial',
    authors: 'Christopher L H Chen<sup>1,2</sup> &nbsp;|&nbsp; Trong Hung Nguyen<sup>3</sup> &nbsp;|&nbsp; Simeon Marasigan<sup>4</sup> &nbsp;|&nbsp; Chun Fan Lee<sup>5</sup> &nbsp;|&nbsp; Qingshu Lu<sup>5</sup> &nbsp;|&nbsp; Nagaendran Kandiah<sup>6</sup> &nbsp;|&nbsp; Deidre de Silva<sup>7</sup> &nbsp;|&nbsp; Eddie Chong<sup>1,2</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>8</sup>',
    affiliations: [
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'University of Medicine and Pharmacy at Ho Chi Minh City, Vietnam',
      'Medical City, Manila, Philippines',
      'Duke-NUS Medical School, Singapore',
      'National Neuroscience Institute, Singapore',
      'National Neuroscience Institute, Singapore General Hospital Campus, Singapore',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
    ],
    correspondence: 'Christopher Chen, Department of Pharmacology, NUS. Email: phccclh@nus.edu.sg',
    abstract: [
      { h: 'BACKGROUND', t: 'MLC901 (NeuroAid II) is a traditional Chinese medicine formulation with potential neuroprotective properties proposed for cognitively impaired not demented (CIND) patients.' },
      { h: 'METHODS', t: 'Multi-centre pilot double-blind placebo-controlled RCT in cognitively impaired not demented patients across Singapore, Vietnam, and the Philippines.' },
      { h: 'RESULTS', t: 'MLC901 appears to be safe; there was no significant cognitive benefit in the broader CIND population. Exploratory analysis suggested potential benefits in a subgroup with pre-existing executive function impairment.' },
      { h: 'CONCLUSIONS', t: 'A larger powered trial is warranted to assess efficacy of MLC901 in specific CIND subgroups defined by executive dysfunction at baseline.' },
    ],
    keywords: 'MLC901, NeuroAid, CIND, randomized trial, neuroprotection, cognitive impairment',
  },
  {
    color: '#455a64',
    journal: 'Journal of the American Medical Directors Association',
    jsub: 'ELSEVIER / AMDA',
    doi: '10.1016/j.jamda.2020.03.022',
    volume: 'J Am Med Dir Assoc. 2020;21(6):879-883.e1',
    received: '5 October 2019', revised: '12 February 2020', accepted: '28 February 2020',
    title: 'Psychometric Properties of the National Institute of Neurological Disorders and Stroke and Canadian Stroke Network Neuropsychological Battery in an Asian Older Adult Sample',
    authors: 'Kimberly A Chew<sup>1</sup> &nbsp;|&nbsp; Eddie J Y Chong<sup>1,2</sup> &nbsp;|&nbsp; Christopher L H Chen<sup>1,2</sup> &nbsp;|&nbsp; Xin Xu<sup>1,2</sup>',
    affiliations: [
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
    ],
    correspondence: 'Xin Xu, Department of Pharmacology, NUS. Email: summer.xu@nus.edu.sg',
    abstract: [
      { h: 'OBJECTIVE', t: 'This study established psychometric properties of the NINDS-CSN neuropsychological battery in cognitively normal older adults in Singapore.' },
      { h: 'METHODS', t: '105 cognitively normal older adults (age >=50) were assessed at baseline and 3-month follow-up using both 60-minute and 5-minute battery protocols.' },
      { h: 'RESULTS', t: 'Test-retest reliability ranged from r = 0.36–0.87. The 60-minute protocol showed excellent concurrent validity (r = 0.83) against a locally validated neuropsychological battery.' },
      { h: 'CONCLUSION', t: 'The NINDS-CSN is reliable and valid for assessing cognitive function in older Asian adults, with applications beyond vascular cognitive impairment.' },
    ],
    keywords: 'NINDS-CSN neuropsychological battery, memory clinic, reliability, validity',
  },
  {
    color: '#424242',
    journal: 'Diagnostics',
    jsub: 'MDPI',
    doi: '10.3390/diagnostics5040475',
    volume: 'Diagnostics. 2015;5(4):475-486',
    received: '10 August 2015', revised: '15 October 2015', accepted: '2 November 2015',
    title: 'Beyond Screening: Can the Mini-Mental State Examination be Used as an Exclusion Tool in a Memory Clinic?',
    authors: 'Xin Xu<sup>1,2</sup> &nbsp;|&nbsp; Eddie Chong<sup>1,2</sup> &nbsp;|&nbsp; Saima Hilal<sup>1,2,3</sup> &nbsp;|&nbsp; Mohammad Kamran Ikram<sup>4</sup> &nbsp;|&nbsp; Narayanaswamy Venketasubramanian<sup>5</sup> &nbsp;|&nbsp; Christopher Chen<sup>1,2</sup>',
    affiliations: [
      'Department of Pharmacology, Yong Loo Lin School of Medicine, NUS',
      'Memory Aging and Cognition Centre, National University Health System, Singapore',
      'Saw Swee Hock School of Public Health, National University of Singapore',
      'Duke-NUS Graduate Medical School, Singapore',
      'Raffles Neuroscience Centre, Raffles Hospital, Singapore',
    ],
    correspondence: 'Xin Xu, Department of Pharmacology, NUS. Email: phcxx@nus.edu.sg',
    abstract: [
      { h: 'OBJECTIVE', t: 'This study examined whether the MMSE can be used as an exclusion tool rather than only a screening tool in memory clinic settings.' },
      { h: 'METHODS', t: 'Patients underwent the MMSE followed by standardized neuropsychological assessments leading to consensus diagnostic classification.' },
      { h: 'RESULTS', t: 'When stratified by education level and using optimal likelihood ratios, a higher percentage of patients were correctly identified with minimal misclassification.' },
      { h: 'CONCLUSIONS', t: 'The MMSE has utility as an exclusion tool at education-specific cut-points, potentially streamlining memory clinic workflows.' },
    ],
    keywords: 'Mini-Mental State Examination, cognitive assessment, dementia, memory clinic, exclusion criteria',
  },
];n

// ── Folder configs ───────────────────────────────────────────────────────────
